#!/usr/bin/env bash
#
# Build a release APK locally and sign it with this machine's own keystore.
#
# Why re-sign instead of editing android/app/build.gradle: `android/` is
# generated by `expo prebuild` and gitignored, so any signing config written
# into it is lost the next time it is regenerated. Re-signing the finished APK
# survives that, and keeps every local build on one signature — which is what
# lets a new build install over the previous one instead of demanding an
# uninstall (and taking the device database with it).
#
# Expo's generated release config signs with the debug keystore; apksigner
# replaces that signature block wholesale.
set -euo pipefail

MOBILE="$(cd "$(dirname "$0")/.." && pwd)"
export ANDROID_HOME="${ANDROID_HOME:-C:/Users/haruhadj/scoop/apps/android-clt/current}"

# Forced, not defaulted. The shell inherits JAVA_HOME=temurin-lts (JDK 25),
# and `${JAVA_HOME:-…}` would keep it — which fails deep in the native build:
#   Execution failed for task ':react-native-worklets:configureCMakeRelWithDebInfo'
#   > WARNING: A restricted method in java.lang.System has been called
# AGP for RN 0.86 wants 17. Override with NEKOSTREAM_JDK if that ever changes.
export JAVA_HOME="${NEKOSTREAM_JDK:-C:/Users/haruhadj/scoop/apps/temurin17-jdk/current}"

KEYSTORE="$MOBILE/credentials/nekostream-release.keystore"
PASS="${NEKOSTREAM_KEYSTORE_PASS:-nekostream}"
BUILT="$MOBILE/android/app/build/outputs/apk/release/app-release.apk"
SIGNED="$MOBILE/android/app/build/outputs/apk/release/nekostream-signed.apk"
APKSIGNER="$ANDROID_HOME/build-tools/36.0.0/apksigner.bat"

if [ ! -f "$KEYSTORE" ]; then
  echo "No keystore at $KEYSTORE — generate one with keytool first." >&2
  exit 1
fi

cd "$MOBILE/android"

# Force the JS to be re-bundled.
#
# `createBundleReleaseJsAndAssets` reported UP-TO-DATE after a change to
# mobile/src/, and shipped an APK whose native side was fresh and whose
# JavaScript was one build old — which looks exactly like "the fix did not
# work" on the device. Deleting its output is cheaper than diagnosing the
# task's input tracking, and re-bundling costs seconds.
rm -rf app/build/generated/assets/react/release

./gradlew assembleRelease

"$APKSIGNER" sign \
  --ks "$KEYSTORE" \
  --ks-key-alias nekostream \
  --ks-pass "pass:$PASS" \
  --key-pass "pass:$PASS" \
  --out "$SIGNED" \
  "$BUILT"

"$APKSIGNER" verify --print-certs "$SIGNED" | head -3
echo "signed APK: $SIGNED"
