/** Shared Android color roles and type scale for the anime shelf. */
export const theme = {
  color: {
    background: "#131217",
    surface: "#211E29",
    surfaceRaised: "#2B2635",
    accentContainer: "#393044",
    border: "#3B3445",
    muted: "#BBB3C5",
    foreground: "#F4F0FA",
    accent: "#CBBBF7",
    accentHover: "#DDD1FF",
    accentForeground: "#292039",
    anilist: "#02a9ff",
    mal: "#8BA6E8",
    amber: "#F2C873",
    amberText: "#F4D593",
    amberFill: "#6D5325",
    amberBorder: "#6D5325",
    danger: "#FFB4AB",
    success: "#A3D5B4",
  },
  type: {
    headline: {
      fontSize: 30,
      lineHeight: 38,
      fontWeight: "700" as const,
      letterSpacing: -0.6,
    },
    title: {
      fontSize: 20,
      lineHeight: 28,
      fontWeight: "700" as const,
      letterSpacing: -0.3,
    },
    section: { fontSize: 18, lineHeight: 26, fontWeight: "600" as const },
    body: { fontSize: 14, lineHeight: 22 },
    label: { fontSize: 13, lineHeight: 18, fontWeight: "600" as const },
    caption: { fontSize: 12, lineHeight: 18 },
  },
} as const;
